=== EmortalMC/k8s-configs/minecraft/config/schema/gamemode.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "gamemode",
  "type": "object",
  "required": [
    "id",
    "enabled",
    "fleetName",
    "friendlyName",
    "activityNoun",
    "minPlayers",
    "maxPlayers",
    "partyRestrictions",
    "matchmakerInfo"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "The game mode ID. Must be unique, otherwise updates may break.",
      "pattern": "^[a-z-]+$"
    },
    "enabled": {
      "type": "boolean"
    },
    "fleetName": {
      "type": "string",
      "description": "The Agones Fleet name to use for game server allocations."
    },
    "priority": {
      "type": "number",
      "minimum": 0,
      "maximum": 4294967296,
      "default": 0
    },
    "friendlyName": {
      "type": "string",
      "description": "The name shown to the user in user interfaces."
    },
    "activityNoun": {
      "type": "string",
      "description": "The noun used to describe the activity in user interfaces. Used in the sentence 'BomBardyGamer <activityNoun> <friendlyName>.'"
    },
    "minPlayers": {
      "type": "number",
      "description": "The minimum number of players required to start a game.",
      "minimum": 1
    },
    "maxPlayers": {
      "type": "number",
      "description": "The maximum number of players allowed in a game.",
      "minimum": 1
    },
    "displayItem": {
      "type": "object",
      "default": null,
      "$ref": "#/$defs/item"
    },
    "displayNpc": {
      "type": "object",
      "default": null,
      "$ref": "#/$defs/npc"
    },
    "partyRestrictions": {
      "type": "object",
      "required": [
        "minSize"
      ],
      "properties": {
        "minSize": {
          "type": "number",
          "minimum": 1
        },
        "maxSize": {
          "type": "number",
          "minimum": 1
        }
      }
    },
    "maps": {
      "type": "object",
      "default": null,
      "additionalProperties": {
        "$ref": "#/$defs/map"
      }
    },
    "matchmakerInfo": {
      "type": "object",
      "required": [
        "matchMethod",
        "selectMethod",
        "rate"
      ],
      "properties": {
        "matchMethod": {
          "type": "string",
          "enum": [
            "INSTANT",
            "COUNTDOWN"
          ]
        },
        "selectMethod": {
          "type": "string",
          "enum": [
            "PLAYER_COUNT",
            "AVAILABLE"
          ]
        },
        "rate": {
          "type": "number",
          "minimum": 0
        },
        "backfill": {
          "type": "boolean",
          "default": false
        }
      }
    }
  },
  "$defs": {
    "item": {
      "type": "object",
      "required": [
        "material",
        "slot",
        "name"
      ],
      "properties": {
        "material": {
          "type": "string",
          "description": "The material namespaced ID of the item to display.",
          "$comment": "This pattern is from Adventure.",
          "pattern": "(?:([a-z0-9_\\-.]+:)?|:)[a-z0-9_\\-./]+"
        },
        "slot": {
          "type": "number",
          "description": "The inventory slot to place the item in",
          "minimum": 0
        },
        "name": {
          "type": "string",
          "description": "The name to display, in MiniMessage format."
        },
        "lore": {
          "type": "array",
          "description": "The lore lines to display, in MiniMessage format.",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "map": {
      "type": "object",
      "required": [
        "id",
        "enabled",
        "friendlyName",
        "priority",
        "displayItem"
      ],
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[a-z]+$"
        },
        "enabled": {
          "type": "boolean"
        },
        "friendlyName": {
          "type": "string"
        },
        "priority": {
          "type": "number",
          "minimum": 0
        },
        "displayItem": {
          "$ref": "#/$defs/item"
        }
      }
    },
    "npc": {
      "type": "object",
      "required": [
        "entityType",
        "titles",
        "skin"
      ],
      "properties": {
        "entityType": {
          "type": "string"
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "skin": {
          "$ref": "#/$defs/skin"
        }
      }
    },
    "skin": {
      "type": "object",
      "required": [
        "texture",
        "signature"
      ],
      "properties": {
        "texture": {
          "type": "string"
        },
        "signature": {
          "type": "string"
        }
      }
    }
  }
}

=== EmortalMC/k8s-configs/minecraft/config/gamemodes/125-tower-defence.json
{
  "id": "towerdefence",
  "enabled": true,
  "fleetName": "towerdefence",

  "priority": 125,

  "friendlyName": "TowerDefence",
  "activityNoun": "playing",

  "minPlayers": 2,
  "maxPlayers": 12,

  "displayItem": {
    "material": "minecraft:totem_of_undying",
    "slot": 20,
    "name": "<gradient:#ffb70f:#ffcd17:#ffb70f><bold>TowerDefence</bold></gradient>",
    "lore": [
      "<gray>Towerdefence is a fast-paced PvP game where</gray>",
      "<gray>quick reflexes and strategic tower building</gray>",
      "<gray>are essentialto fend off enemy mobs and stay</gray>",
      "<gray>ahead of the competition.</gray>"
    ]
  },

  "displayNpc": {
    "entityType": "PLAYER",
    "titles": [
      "<gradient:#ffb70f:#ffcd17:#ffb70f><bold>TowerDefence</bold></gradient>"
    ],
    "skin": {
      "texture": "ewogICJ0aW1lc3RhbXAiIDogMTYyMDQ4MzM1ODQ2OSwKICAicHJvZmlsZUlkIiA6ICI1NjY3NWIyMjMyZjA0ZWUwODkxNzllOWM5MjA2Y2ZlOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVJbmRyYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mMjUxNjljNGM4YmUyYjc4MWQyNzE0ZDA5M2I0ZDc2MTA3MTFmMWZmMTlkZjYyYjg2MjZjMzNmZWNjZGY3Yjg5IgogICAgfQogIH0KfQ==",
      "signature": "laCteZJ6UWQOot+RUG011rFs1g5AnZX1tSJEXeia658pNkOrbTNfXS1GK9KQYROg4bFK1VQ/S0N/qbIbQgPJwvoKUJjNExm4D8MKuiFilfk5YolZgkUIfD6ff6dv/wfuU36Zx21UZjDwqRPcIfmcPI2trrp3qmoH6H/6Qh1z9GlI7emK437jgEQSjkCanP9U4/iJ5lrUVt+phKVhXT/RsVeIqUzuCwD7YoTAQAErCdrTdkNfk8e8utIyPdafmLhASaoUarpspi2pbg0QrgnBQlXEl9l3nNJ89dwxRuy0YiMEgHdnzd++Rj6JVvk/d55T1EK5ymm2gICLsZUJidxemmSlS2vkSifHRlMbcWbWrDDPj2svbv9/707jDGJ6XV1ZCdCh0JZTvb1QKavKFypgfC6hipwStTuqskwp3Kq6d65F1QkNxBUsH4jFk1Re5TTAT6qp4D8C5vyUHUBJD35ypdRG3OjZl2a9iH2RWIvmHoYkAc3awxcJD75olX0HNoZ58Yex7x9g0cg/kiT76/g936YxM1rmxo6s21jQh/GsRyS2zsy9OGY8ivqb2UJ0alwPzwtDPLHgyYYk3NTay02N/iwWeo46uuhP7P3erTumjPYoGM6gtwcILdqJqkT27BuRYcyCFg/K9CzV9mdqOFu/vA7jBLEutDv+kC/l7UC/FnU="
    }
  },

  "partyRestrictions": {
    "minSize": 1,
    "maxSize": 12
  },

  "maps": {
    "default": {
      "id": "default",
      "enabled": true,

      "friendlyName": "Default",
      "priority": 100,

      "displayItem": {
        "slot": 0,
        "material": "minecraft:barrier",
        "name": "<green><bold>Default</bold></green>"
      }
    }
  },

  "matchmakerInfo": {
    "matchMethod": "COUNTDOWN",
    "selectMethod": "AVAILABLE",
    "rate": 750000000
  }
}

=== EmortalMC/k8s-configs/minecraft/config/gamemodes/130-battle.json
{
  "id": "battle",
  "enabled": true,
  "fleetName": "battle",

  "priority": 130,

  "friendlyName": "Battle",
  "activityNoun": "playing",

  "minPlayers": 2,
  "maxPlayers": 12,

  "displayItem": {
    "material": "minecraft:iron_sword",
    "slot": 24,
    "name": "<gradient:#ffc34d:#ffaa00><bold>Battle</bold></gradient>",
    "lore": [
      "<gray>The console survival games experience.</gray>",
      "<gray>Find loot, find player, kill player,</gray>",
      "<gray>find another player, kill other player,</gray>",
      "<gray>repeat until win</gray>"
    ]
  },

  "displayNpc": {
    "entityType": "PLAYER",
    "titles": [
      "<gradient:#ffc34d:#ffaa00><bold>Battle</bold></gradient>"
    ],
    "skin": {
      "texture": "ewogICJ0aW1lc3RhbXAiIDogMTYxOTQzOTEzMjA4MiwKICAicHJvZmlsZUlkIiA6ICI5MThhMDI5NTU5ZGQ0Y2U2YjE2ZjdhNWQ1M2VmYjQxMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWV2ZWxvcGVyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzgzYmVkNGJiZDc5NmE5MWEyZjE5ZjE2ZTljMDIxMWRiMTFhM2Y4MDk0M2UwZTljODJlNjMxM2I1OWVkZDgxOTEiCiAgICB9CiAgfQp9",
      "signature": "SFO9i3hwfOOfhNapOWUJ/QiQ8orq47Ld6nCV2xPXNZH9WtOkw+FNJZrDIrxdp0SPA4VaN+7BQL1mq5uHTgGov55KHsJxoeQGvvWKDWeG+V+DsYzkf+34LY6BYWhKdnGNP2EDt/snT3wca9ju8McUsxiqHXkX6UTU68Zj7xFk1HVtusQIjyakva4ST6WB4BdYy6BlLl6ckKo+kGF+aSMhhok8znhwypkO7gGBtK4fYgpuW7I8C2lBn+myGASndikw/CBpuYaUTj1xECdTb0O6Tys937EBkHeELoxoflgkxTBe37DHDCxoQKTnXV28yV+uXOIoNp7botUSho5x5GELqg4T6ma97hjF5Cp1x+3ekZcxx3u0Io2/ifb79p+DBfBkfs50oixWIBXJV4DaZaTgE1MQtRGQBe/baHap5+aeC9LAcCPVBzwMuM7kUqQ0RGv72FaPEojhYU1PvVUC0E+BfQvtg6M19zYJL27OB1Ik9rHAC7U18ilGiGOwUgLoetYIy2JYFGO57cE0MhLe9ERr2kjNFCbwO8l1cWhBpRzMfrr6PQAKFQjt/APPouYH7PNO7eu/vOSy8BcJw3g2tDg79NryUNLO0vkgTVz4+Fr5wkRD3QmieM0Gtv26h+vev9ZKIrSylvpEQkyeSTXrvHov4gtI+m4yfHb8pwdFlZDJSlY="
    }
  },

  "partyRestrictions": {
    "minSize": 2,
    "maxSize": 8
  },

  "maps": {
    "cove": {
      "id": "cove",
      "enabled": true,

      "friendlyName": "Cove",
      "priority": 100,

      "displayItem": {
        "slot": 0,
        "material": "minecraft:barrier",
        "name": "<green><bold>Cove</bold></green>"
      }
    }
  },

  "matchmakerInfo": {
    "matchMethod": "COUNTDOWN",
    "selectMethod": "AVAILABLE",
    "rate": 750000000
  }
}

=== EmortalMC/k8s-configs/minecraft/config/gamemodes/105-marathon.json
{
  "id": "marathon",
  "enabled": true,
  "fleetName": "marathon",

  "priority": 105,

  "friendlyName": "Marathon",
  "activityNoun": "playing",

  "minPlayers": 1,
  "maxPlayers": 100,

  "displayItem": {
    "material": "minecraft:grass_block",
    "slot": 16,
    "name": "<red><bold>Marathon</bold></red>",
    "lore": [
      "<gray>An infinitely generating,",
      "<gray>endless parkour gamemode.",
      "<gray>See how far you can go!"
    ]
  },

  "displayNpc": {
    "entityType": "PLAYER",
    "titles": [
      "<red><bold>Marathon</bold></red>"
    ],
    "skin": {
      "texture": "ewogICJ0aW1lc3RhbXAiIDogMTcyNDI5Mzc1MTM4NywKICAicHJvZmlsZUlkIiA6ICIyMjYwMWIxMGY0MTc0ZjA3OWIwYWM2MGE5NGEzOTBmYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJ1bmRlcmdhbWVndXkiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODIyOWI4ZTVjYWM0OGE5OGY1ZjQxOTIzYjcxMWJkMjYwMzdlOGFiNzVkMDQ3ZTM1ZGQ2ZTFmYmRhMGJlY2FkNyIKICAgIH0KICB9Cn0=",
      "signature": "J+TIgPB/VFJEucLlUrFzpQM6sXYS2nZ43JCaBfmY7gXRR+0SRfHsc5bSKGALAP+Rydict3yg2ixfkOEC61LijpcgfsQBVpRuqIm837E9wEG6KwSTRRw3ydLvMTYIr6JKIE5OCsn37FC97Tf0MVR6CgzGyQySFhbLEXNTDr+5LF0DWtXR+TzDngupXqzf2ZqWxvkFdhv6mTFAYdRVbxN9AQRaFGyEcBi9f4nHsVnB7o6WoJWpy7XsSEQR7BmUzDijs6R42RAdoLerF47aDDJBiMNDLcsiTOPzugxJ9vGqpQtkw5cnZbjSvD30KtQPLtCFgDek+RaRIv0v48FERigk7rR1EIIHybJ8ODUu9mfMhQ6skEZsYg5vE+v/ybHC/5nqmQYR1C1thqzPRLUBT+ZqnjuC72RK4eh9OlJ1Usrla3/YJ630+8/Pmlu4K1VapQX+mZEuT1/Hk7QBPvzLBqkgRnkyD5o3kd8XHWJzp0s5J3qXSTfdJCznbTKD2tl7xkkimUJAciO0Tazg7x/UkNRL+0f5a9jhFJAZprNg1hV1jRlGiJJT1MUxziZ2EYOx8mMJ9H9S4JMT7JRITDXsCO6C2EF+HemHAN1GQBOQ1y0L1usu7nML1mthVUB9FSjcJ1C1m4fNY7tEb7eGHkvN5uH7MWmw7943wwIbv3xb6W5KDHU="
    }
  },

  "partyRestrictions": {
    "minSize": 1,
    "maxSize": 100
  },

  "matchmakerInfo": {
    "matchMethod": "INSTANT",
    "selectMethod": "PLAYER_COUNT",
    "rate": 175000000
  }
}

=== EmortalMC/k8s-configs/minecraft/config/gamemodes/110-lazertag.json
{
  "id": "lazertag",
  "enabled": true,
  "fleetName": "lazertag",

  "priority": 110,

  "friendlyName": "LazerTag",
  "activityNoun": "playing",

  "minPlayers": 2,
  "maxPlayers": 12,

  "displayItem": {
    "material": "minecraft:netherite_hoe",
    "slot": 11,
    "name": "<gradient:gold:yellow><bold>LazerTag</bold></gradient>",
    "lore": [
      "<gray>Battle it out with weird and wacky guns.",
      "<gray>The first player to 25 kills wins!"
    ]
  },

  "displayNpc": {
    "entityType": "PLAYER",
    "titles": [
      "<gradient:gold:yellow><bold>LazerTag</bold></gradient>"
    ],
    "skin": {
      "texture": "ewogICJ0aW1lc3RhbXAiIDogMTYxNDA3NzE5MzQ4MiwKICAicHJvZmlsZUlkIiA6ICJkMGI4MjE1OThmMTE0NzI1ODBmNmNiZTliOGUxYmU3MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJqYmFydHl5IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E0NjQxMmMzOTgwODZlYzMxMzIxMzlhMTE5NWU0ODNlMGE0OWRmYThiZWMzZWIxNDc0ZjViMTliMTY0NTE4NmUiCiAgICB9CiAgfQp9",
      "signature": "krIl4GecgEcDkkEG2DpUvZWnIqpxhJRcFhkaWYYG9A35u49mGkM3eHJX1ys60lF042EXiPpujonZt4Kp8NF0Hn1WblxfnJUfu1o97Tv7iI+vfB2M/cIfEAKnqVvagPkWvhf6N9TITF7szQc6j0ksMNrFv+gV0NKDZFoQPgw+q+ADGPicQdDpub0rr6hzPmv1H1kNQxDgLGxwIAV4fzVToGKRqLKLCHSMC64d3/GJkrtxQzsvnWji9nD3WJzilLmKN7yjB8Cs1xAWTfxIdayeT/k6pDADyqlRs9PCfGISEwMQKHz0kOqNBDA5J6UB08q7zhO1uZyW4v3QaIXXQeyp7dWkffFdRedcNovmWpiOLnC4u8XF5kFUySkvZg4nMHvO+Vr20uFhxiZ7EWaNt1syfNMDEwiZ8oqljTtbEPUhpj68n1hViThhbatj1XeEa6zSqB1pmDw36q+QQUKX4Q894uDXMr6Gij/1LNJ00rfNoDN43UXt29XPN/qQ1Pj5TXctJdV8zBVhrK60qDpII8miHlslGTTwwpMKgEh5K0JJ5xWtmk4tY4TON0RsQ4RjD+UxmfrPDgOyAXoRxWnPVeUldODbkFHn8wMnK6M/k5g8AFOGOM5h8CfnjDqUeiyZPYC6EihC0dxK9yzPZxe2av27LiHUYDWDs3P5zKVKXRbFaR8="
    }
  },

  "partyRestrictions": {
    "minSize": 1,
    "maxSize": 12
  },

  "matchmakerInfo": {
    "matchMethod": "COUNTDOWN",
    "selectMethod": "AVAILABLE",
    "rate": 2000000000
  }
}

=== EmortalMC/k8s-configs/minecraft/config/gamemodes/135-minesweeper.json
{
  "id": "minesweeper",
  "enabled": true,
  "fleetName": "minesweeper",

  "priority": 110,

  "friendlyName": "Minesweeper",
  "activityNoun": "solving",

  "minPlayers": 1,
  "maxPlayers": 10,

  "displayItem": {
    "material": "minecraft:tnt",
    "slot": 14,
    "name": "<green><bold>Minesweeper</bold></green>",
    "lore": [
      "<gray>Try not to anger your friends",
      "<gray>while sabotaging 90% of your games,",
      "<gray>while also trying to clear the minefield"
    ]
  },

  "displayNpc": {
    "entityType": "PLAYER",
    "titles": [
      "<green><bold>Minesweeper</bold></green>"
    ],
    "skin": {
      "texture": "ewogICJ0aW1lc3RhbXAiIDogMTY0Mjk3NzYxNjg4NCwKICAicHJvZmlsZUlkIiA6ICIwYTUzMDU0MTM4YWI0YjIyOTVhMGNlZmJiMGU4MmFkYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJQX0hpc2lybyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84NzhjODZlYTMyYmFiZTAxOGY3MzFlNTNjMDE4MmQ0YzVlNWU3Y2MwOWQ5MzMxOTJkYmY1ZWE1YWRlZTNlZDAiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ==",
      "signature": "U3/TuEu6d7noBtYaQr98/1nI2HqfqNRrymbvVtVZz1dn/Cx4Qr4qiDwbs2buYrPJK1Opv3Cw4/zq5nYE0xc/VYtyGYHUIlE5dbqtYCPfbGYNbBivQXfFhrCndsQjKZbzzjGKVNJPQrvigBKIVV8TP/ylak8eQUtUncTTPOU8K7EjhIbqpwN/qZUgq7aDWvUUZnWV8I6cYwDSETdBZ+UxhoTMzO8+Vnhlo2OzmHtoICLQuZI3qE8ZGPdw35r14oNddPtLdUQ1NGvt7i7dHoeIPDQt68vUq6z6sejqORoXpWgAlIyCvgO5L5yHX58DfqEq7FwECB4q+fXyXVyZLmiiVSDH+wkczyzoUgE2f1hW6ONJ9QiH8n1+PU5Sx37EByTZxOQvOvS+Pj++zYtZHCRzCjcRg6j6u1RnKDteuccywN+bUulCZ7pJavtqMS6XCHd3mQecVUcT8F/jcPmsh2ta27VyueUGQS3ICcM0jiTEaM31ttrVUDszxNqmkmfX1W6MPd2nHXBSaUAWSaXjfdcyKxBOKwV6IxO8Kwjq9SIw5P5KuLdZ2s0m8SgFWIP+sZQI7IsIz0pfxNq9JlHykslQMhux9MOwQNDS29wfI6fGlLCiL1U9xueZAZn4DBp+rIgoXXz4PNxsSkHG7Bvlb5R3v2hK3UZdFDcTkRcU0Io6i2w="
    }
  },

  "partyRestrictions": {
    "minSize": 1,
    "maxSize": 100
  },

  "matchmakerInfo": {
    "matchMethod": "INSTANT",
    "selectMethod": "AVAILABLE",
    "rate": 175000000
  }
}
